forStudents/urls.py
from django.conf.urls import  url
from . import views
from .views import SignUpView

app_name = 'forStudents'
urlpatterns = [
    url(r'^/results/', views.results, name='results'),
    url(r'^test/(\d+)', views.question_of_test, name='question_of_test'),
    url(r'^(\d+)/vote/', views.vote, name='vote'),
    url(r'^(\d+)/detail', views.detail, name='detail'),
    url('signup', SignUpView.as_view(), name='signup'),
    url(r'', views.index, name='index'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from forStudents.urls import urlpatterns
from django.contrib.auth.views import LoginView

urlpatterns = [
    url(r'^start/', include('forStudents.urls')),

    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^login/', LoginView.as_view(), name='login'),
]

forStudents/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User


class Tests(models.Model):
    nameOfTest = models.CharField(max_length=250)
    limit = models.IntegerField(default=0)

    def __str__(self):
        return self.nameOfTest


class Tryes(models.Model):
    user = models.ForeignKey(User)
    test = models.ForeignKey(Tests)
    count = models.IntegerField(default=0)


class Question(models.Model):
    parent_test = models.ForeignKey(Tests, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    number = models.IntegerField()

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.BooleanField(default=False)
    right = models.BooleanField(default=False)
    score = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

forStudents/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth import authenticate, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.template import loader
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic
from forStudents.models import Question, Choice, Tests, Tryes


@login_required(login_url='/accounts/login/')
def index(request):
    latest_tests_list = Tests.objects.all()
    context = {'latest_tests_list': latest_tests_list}
    return render(request, 'forStudents/index.html', context)


def question_of_test(request, test_id):
    for votes in Choice.objects.filter(votes=True):
        votes.votes = False
        votes.save()
    latest_question_list = Question.objects.filter(parent_test=test_id).order_by('number')
    template = loader.get_template('forStudents/question_of_test.html')
    try:
        tryes = Tryes.objects.get(user=request.user, test__id=test_id)
    except:
        tryes = Tryes(user=request.user, test=Tests.objects.get(id=test_id), count=0)
        tryes.save()
    if tryes.count < 3:
        context = {
            'latest_question_list': latest_question_list,
        }
        return render(request, 'forStudents/question_of_test.html', context)
    else:
        context = {
            'fail': u'Больше нельзя проходить этот тест',
        }
        return render(request, 'forStudents/question_of_test.html', context)


def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Вопросы не созданы")
    return render(request, 'forStudents/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'forStudents/results.html', {'question': question})


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
        selected_choice.votes = True
        selected_choice.save()
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'forStudents/detail.html', {
            'question': question,
            'error_message': "Требуется ответ на вопрос",
        })
    else:
        latest_question_list = Question.objects.filter(parent_test=question.parent_test).order_by('-pub_date')[:5]
        #        if question.number< max(Question.objects.values('number')).get('number'):
        if question.number < max(latest_question_list.values('number')).get('number'):
            return render(request, 'forStudents/detail.html',
                          {'question': get_object_or_404(Question,
                                                         number=question.number + 1)})

        truelist = Choice.objects.filter(question__in=latest_question_list.values('id'), votes=True)
        score = 0
        for i in truelist:
            score = score + i.score
        if score > Tests.objects.get(id=question.parent_test.id).limit:
            res = 'Тест пройден'
        else:
            res = 'Тест провален'
        tryes = Tryes.objects.get(user=request.user, test__id=question.parent_test.id)
        tryes.count = tryes.count + 1
        tryes.save()
        return render(request, 'forStudents/results.html', {'question': question,
                                                            'latest_question_list': latest_question_list,
                                                            'truelist': truelist, 'truecol': truelist,
                                                            'truecol': len(truelist), 'score': score,
                                                            'tryes': tryes.count, 'res': res})


def login(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            render(request, 'forStudents/start/')


class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'forStudents/signup.html'


def logout_view(request):
    logout(request)

forStudents/templates/forStudents/base.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<!-- templates/base.html -->
{% load static %}
<html>
<head>

    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
          rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<div>
    <header>
        <div class="nav-left">
            <h1><a href="{% url 'forStudents:index' %}">Django blog</a></h1>
        </div>
    </header>
    {% if user.is_authenticated %}
    <p>Hi {{ user.username }}!</p>
    <p><a href="{% url 'logout' %}">Log out</a></p>
    {% else %}
    <p>You are not logged in.</p>
    <a href="{% url 'login' %}">Log In</a>
    {% endif %}
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

forStudents/templates/forStudents/detail.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<form action="{% url 'forStudents:vote' question.id %}" method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="checkbox" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
    <input type="submit" value="Vote">


</form>

forStudents/templates/forStudents/index.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

{% if latest_tests_list %}
<ul>
    {% for tests in latest_tests_list %}
    <li><a href="{% url 'forStudents:question_of_test' tests.id %}">{{ tests.nameOfTest }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>Нет тестов. Обратитесь к администратору, чтобы он их создал через админку.</p>
{% endif %}
<p><a href="{% url 'logout' %}">Разлогиниться </a></p>
<p><a href="{% url 'forStudents:signup' %}">Регистрация</a></p>

forStudents/templates/forStudents/logged_out.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

{%extends base.html%}
{% block content %}
<p>Logged out!</p>  

<a href="{% url 'login'%}">Click here to login again.</a>
{% endblock %}

forStudents/templates/forStudents/login.html
<!-- templates/registration/login.html -->
<!-- templates/base.html -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

{% load static %}
<html>
<head>
    <title>Здравствуйте</title>
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400"
          rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
<div>
    <header>
        <div class="nav-left">
            <h1><a href="{% url 'forStudents:index' %}">Django blog</a></h1>
        </div>
    </header>
    {% if user.is_authenticated %}
    <p>Hi {{ user.username }}!</p>
    {% else %}
    <p>You are not logged in.</p>
    <a href="{% url 'forStudents:login' %}">Log In</a>
    {% endif %}
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>
&nbsp;{% block content2 %}
<h2>Log In</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Log In</button>
</form>
{% endblock content2 %}

forStudents/templates/forStudents/post_edit.html
{% extends 'forStudents/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.question_text }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

forStudents/templates/forStudents/question_of_test.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

{% if latest_question_list %}
<ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'forStudents:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>В данном тесте нет вопросов.</p>
{% endif %}
{% if fail %}
<p> {{fail}}</p>
<a href="{% url 'forStudents:index' %}">Ещё поотвечаем?</a>
{%endif %}
<p><a href="{% url 'logout' %}">Log out</a></p>

forStudents/templates/forStudents/results.html
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

<h1> Список верных ответов </h1>


{% if latest_question_list %}
<ul>
    <script>
        var normrezult = 0
    </script>
    {% for questioni in latest_question_list %}
    {% for choice in questioni.choice_set.all %}
    {% if choice.right %}
    <li>{{ choice.choice_text }} &#45;&#45; {{ choice.votes }}</li>
    {%endif%}
    {% endfor %}
    {% endfor %}
</ul>
</ul>
{% else %}
<p>No questions are available.</p>
{% endif %}
{%if truelist %}
<p>Ваши верные ответы</p>
{%for ch in truelist %}
<li>{{ ch.choice_text }}</li>
{%endfor%}
{%endif%}
<p> Количество верных ответов</p>
<li>{{truecol}}</li>
<p> Количество баллов</p>
<li>{{score}}</li>
<h2>{{res}}</h2>

<p>Количество попыток <p>
    <li>{{tryes}} из 3</li>
<a href="{% url 'forStudents:index' %}">Ещё поотвечаем?</a>

forStudents/templates/forStudents/signup.html
<!-- templates/signup.html -->
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">

{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock content %}

forStudents/templates/forStudents/singup.html
<!-- templates/signup.html -->
{% extends 'base.html' %}
 
{% block content %}
<h2>Sign up</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Sign up</button>
</form>
{% endblock content %}